---
# tasks file for provision-ec2-instance
 - name: provision ec2 linux instance 
   amazon.aws.ec2:
     aws_access_key: '{{aws_access_key}}'
     aws_secret_key: '{{aws_secret_key}}'
     key_name: '{{key_name}}'
     instance_type: '{{instance_type}}'
     image: '{{ ami_id }}'                                 
     wait: yes
     group_id: '{{security_group_id}}'
     count: 1
     vpc_subnet_id: '{{subnet_id}}'
     assign_public_ip: yes
     region: '{{region}}'
   register: op

   - name: debug
     debug:
       var: op.instances[0].public_ip


   - name: get me ip of newly provisioned instance
     copy:
       content: "{{op.instances[0].public_ip}}"
       dest: /tmp/obtained_ip.txt
