---
 - name: Provision an EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: True
   tags: provisioning

   vars:
      instance_type: t2.micro
      security_group: webserver
      image: ami-08962a4068733a2b6
      region: us-east-1
      keypair: EC2keypair
      count: 1    
   
   tasks:
     - name: Create new security group with below given name
       local_action:
               module: ec2_group
               name: "{{ security_group }}"
               description: Security Group for newly created EC2 instance
               region: "{{ region }}"
               rules:
                  - proto: tcp
                    from_ports: 22
                    to_port: 22
                    cidr_ip: 0.0.0.0/0
               rules_egress:
                  - proto: all
                    cidr_ip: 0.0.0.0/0

     - name: Launch the new t2 micro EC2 instance
       local_action: ec2
                     group={{ security_group }} 
                     instance_type={{ instance_type }}
                     image={{ image }}
                     wait=true
                     region={{ region}}
                     keypair={{ keypair }} 
                     count={{ count }} 
       register: ec2
               
     - name: Wait for EC2 Instance tp spin up and ready for SSH access
       local_action: wait_for
                     host={{ item.public_ip }} 
                     port=22
                     state=started
       with_items: "{{ ec2.instance }}" 
     - name: Adding tags to identify
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}" 
       args:
         tags:
           Name: Web Server 
           Owner: Shivani Chaudhary
           Purpose: Testing EC2 Instance  from Ansible         

