---
# tasks file for import_role
- name: importing role from A lib
  import_role:
    name: shivani-shared-library-A/first-role

- name: importing role from B lib
  import_role: 
    name: shivani-shared-library-B/second-role
